=== msmohankumar/CAD-customization-chatbot-/UGII/tab_label_format_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    targetNamespace="http://www.plmxml.org/Schemas/RoutingAutoAnnSchema" 
    xmlns:tab_label_format_schema="http://www.plmxml.org/Schemas/RoutingAutoAnnSchema" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="unqualified" 
    attributeFormDefault="unqualified" 
    xml:lang="en">
<xsd:annotation>
    <xsd:documentation>
     This schema defines a namespace "http"//www.plmxml.org/Schemas/RoutingAutoAnnSchema"
     ( mapped to "tab_label_format_schema" in this document ). 
    
     Tutorial for schema creation:
     http://www.w3schools.com/schema/schema_intro.asp
    
     For other references see apv.xsd
    </xsd:documentation>
</xsd:annotation>

<xsd:element name="Tab_Label_Format_File" type="tab_label_format_schema:format_file">
</xsd:element>

<xsd:complexType name="format_file">
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">

        <xsd:element name="Format" type="tab_label_format_schema:format_list"/>

    </xsd:sequence>
    
    <xsd:attribute name="version" type="xsd:decimal" use="required" fixed="1.0"/>

</xsd:complexType>

<xsd:complexType name="format_list">
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">

        <xsd:element name="Attribute" type="tab_label_format_schema:attrib"/>

    </xsd:sequence>

    <xsd:attribute name="format_name" type="tab_label_format_schema:title"/>

</xsd:complexType>

<xsd:complexType name="attrib">

   <xsd:simpleContent>
       
        <xsd:extension base="xsd:string">

           <xsd:attribute name="display_name" type="tab_label_format_schema:title"/>

        </xsd:extension>

   </xsd:simpleContent>

</xsd:complexType>

<xsd:simpleType name="title">
    <xsd:annotation>
        <xsd:documentation>
            Ensures string is 1->50 characters.
        </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
        <xsd:minLength value="1"/>
        <xsd:maxLength value="50"/>
        <xsd:whiteSpace value="collapse"/>
    </xsd:restriction>
</xsd:simpleType>

</xsd:schema>

=== msmohankumar/CAD-customization-chatbot-/UGII/tab_label_format_file.xml
<?xml version="1.0"?>
<!--
    Sample Automated annotation format file. 
    Implemented UG NX3 
-->
<tab_label_format_schema:Tab_Label_Format_File 
	xmlns:tab_label_format_schema="http://www.plmxml.org/Schemas/RoutingAutoAnnSchema"
	xsi:schemaLocation="http://www.plmxml.org/Schemas/RoutingAutoAnnSchema tab_label_format_schema.xsd" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        version ="1.0"
>

<Format format_name = "Format1">
<!--
    "display_name" is the title which goes on the header row of the
    tabular note. the content of the element Attribute, for example
    run_id is the UG attribute we search for. The tabular note will
    thus have the string corresponding to display_name as the header
    and the value of the attribute as shown below. If the user did
    not define run_id attribute, then the second row will have "" 
    ( empty ) string.  
   
    _________________________________________________
    | Run ID        |                               |
    |_______________|_______________________________|
    | 300           |                               |
    |_______________|_______________________________|
-->
    <Attribute display_name = "Run ID ">
	 run_id
    </Attribute>
    <Attribute display_name = "Flow Code">
	 R$NPS 
    </Attribute>
    <Attribute display_name = "Reference ID">
	 reference_id
    </Attribute>
    <Attribute display_name = "Location">
	 location
    </Attribute>
</Format>

<Format format_name = "Format2">
    <Attribute display_name = "Name">
	 name 
    </Attribute>
    <Attribute display_name = "Owner">
	 owner 
    </Attribute>
    <Attribute display_name = "Fabrication Number">
	 fab_number
    </Attribute>
    <Attribute display_name = "Description">
	 description
    </Attribute>
</Format>

</tab_label_format_schema:Tab_Label_Format_File>
